image: ymotongpoo/hugo:latest

stages:
  - build
  - deploy

build:checkout-repo:
  only: 
  - source
  stage: build
  script:
  - "git checkout source"
  - "git submodule init"
  - "git submodule update --recursisve"

build:hugo-site:
  only:
  - source
  stage: build
  script:
  - "/home/hugo/hugo --theme=tropic"
  artifacts:
    paths:
    - public/
    
deploy:copy-content:
  only:
  - source
  stage: deploy
  before_script:
  - "mkdir -p /tmp/deploy"
  script:
  - "cp -r public/. /tmp/deploy"
  after_script:
  - "rm -rf public"
  dependencies:
  - build:hugo-site

deploy:push-to-master:
  only:
  - source
  stage: deploy
  script:
  - "git checkout master"
  - "git config --global user.email ymotongpoo@gmail"
  - "git config --global user.name Yoshi Yamaguchi"
  - "cp -rf /tmp/deploy/. ."
  - "git add --all"
  - "git commit -m '[gitlab-ci]'"
  - "git push origin master"