image: ymotongpoo/hugo:latest

stages:
  - build
  - deploy

checkout and update repository:
  only: 
    - source
  stage: build
  script:
    - git checkout source
    - git submodule init
    - git submodule update --recursisve

build hugo site:
  only:
    - source
  stage: build
  script:
    - /home/hugo/hugo --theme=tropic

copy content as artifact:
  only:
    - source
  stage: build
  script:
    - cp -r public/. $dir
    - rm -rf public

push content to master:
  only:
    - master
  stage:
    - deploy
  script:
    - git push origin HEAD:master
