baseurl = "https://gist.ymotongpoo.com/"
languageCode = "ja-jp"
title = "depository"

googleAnalytics = "UA-6420772-12"
hasCJKLanguage = true

[params]
  contact = "ymotongpoo+githubio@gmail.com"
  dateformat = "Jan 2, 2006"
  themecolor = "#ffbd43"
  # Fonts settings.
  googlefonts = "https://fonts.googleapis.com/css?family=Lobster|Lato:400,700" # Optional, Include google fonts.
  fontfamily = "Lato,YuGothic,'Hiragino Kaku Gothic Pro',Meiryo,sans-serif" # Optional, Override body font family.
  logofontfamily = "Lobster, cursive" # Optional, Override logo font.
  ampscripts = """
<script async custom-element="amp-twitter" src="https://cdn.ampproject.org/v0/amp-twitter-0.1.js"></script>
<script async custom-element="amp-iframe" src="https://cdn.ampproject.org/v0/amp-iframe-0.1.js"></script>
<script async custom-element="amp-ad" src="https://cdn.ampproject.org/v0/amp-ad-0.1.js"></script>
"""

[taxonomies]
  tag = "tags"

[permalinks]
  tech = "/blog/:year/:month/:day/:slug/"